### PR TITLE
Make files_archive work with oc7

### PR DESCRIPTION
**Pull request by icewind1991**
Also makes them read only to prevent the various data loss isues that existed previously

cc @karlitschek @PVince81

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@icewind1991 rebase required

**Comment by DeepDiver1975** [comment]
(I'm still questioning the need of this app)

**Comment by HLFH** [comment]
@DeepDiver1975 So could you remove it? The files_archive app barely works. It would be better for users not to use this app.

**Comment by larsnaesbye** [comment]
Does it work with OC 8 or newer, though? I'm considering replacing my homebrewed files_compress app if there's an "official" app in an OC version that's newer.

**Comment by PVince81** [comment]
@icewind1991 any update ? This looks old and outdated, especially if it was written for OC 7...

**Comment by icewind1991** [comment]
outdated

**Pull request closed without merging**
