### PR TITLE
Allow seeking for non-public videos. 

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes seek for logged in users
And seeking still doesn't work for guests unfortunately.

### CODE REVIEW

**Comment by VicDeo** [comment]
Ref #2087

**Comment by karlitschek** [comment]
:+1:

**Comment by supportreq** [comment]
@VicDeo this change allowed viewing videos by downloading partial content. In case I want to start viewing the video from 40min, if the file is not downloaded completed it will first complete downloading all the previous 40min and than start.. Can we do something about this?

Thank You

**Comment by MorrisJobke** [comment]
> @VicDeo this change allowed viewing videos by downloading partial content. In case I want to start viewing the video from 40min, if the file is not downloaded completed it will first complete downloading all the previous 40min and than start.. Can we do something about this?

This depends on the video file. The moov atom needs to be at the beginning and not the end: https://walterebert.com/blog/start-playing-mp4-videos-before-download-has-finished/

**Comment by PVince81** [comment]
@VicDeo @karlitschek should this be backported ? Could potentially fix https://github.com/owncloud/apps/issues/2064

**Comment by karlitschek** [comment]
I think we should backport this. :+1:  Very good improvement

**Comment by PVince81** [comment]
@VicDeo told  me this was already in 8.2

**Comment by PVince81** [comment]
unless we want this backported to 8.1 and 8.0 too ? @karlitschek

**Comment by karlitschek** [comment]
makes sense to backport

**Comment by karlitschek** [comment]
and what I mean is to all of it :-)

**Pull request merged**
