### PR TITLE
add icons for files_videoviewer and user_external

### PR DESCRIPTION
**Pull request by jancborchardt**
Fixes https://github.com/owncloud/core/issues/13524

Please review @jnfrmarks @DeepDiver1975

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@karlitschek Should we backport these icons to stable8?

**Comment by karlitschek** [comment]
please backport

**Comment by MorrisJobke** [comment]
I simply cherry-picked them, because that are just icons:

stable8 cf33254
stable8 f7dcf5e

**Pull request merged**
