### PR TITLE
Remove deprecated migrate apps

### PR DESCRIPTION
**Pull request by tomneedham**
@DeepDiver1975

### CODE REVIEW

**Comment by butonic** [comment]
IMO Not having this is not an option. We need to at least support export/import of users files and the corresponding shares in order to be compliant with the https://userdatamanifesto.org/ As a small company admin I may want to start with a hosted oc instance where I am the group admin and then later migrate my users to an on premise solution. Or the other direction when I found a trustworthy provider.

**Comment by butonic** [comment]
@karlitschek close this?

**Comment by tomneedham** [comment]
I agree this feature needs to stay, but yet I don't know of an app that actually maintains export/import functionality through this system. Doesn't this defeat the point? Either we invest time fixing this, and supporting the import/export code in the apps, or remove code that has been broken for months.

**Comment by DeepDiver1975** [comment]
superseded by #1913

**Pull request closed without merging**
