### PR TITLE
[external] fix ownCloud theming error

### PR DESCRIPTION
**Pull request by deMattin**
Fix for issue #2026:
The stylesheet ../apps/external/css/style.css is integrated in the wrong place so this stylesheet loads independent of the fact, if external app is active or not.

### CODE REVIEW

**Comment by karlitschek** [comment]
@LukasReschke @jancborchardt What do you think?

**Comment by karlitschek** [comment]
@DeepDiver1975 what do you think?

**Comment by deMattin** [comment]
Did I make a mistake with my pull request?
Both patches are needed and I only see the 2nd checked?

**Comment by deMattin** [comment]
Should I make a new and "clean" pull request?

**Comment by MorrisJobke** [comment]
@deMattin Would be nice

**Comment by deMattin** [comment]
I made a new pull request: #2036
All checks "green".
Please have a look.

(this one here should be closed)

**Pull request closed without merging**
