### PR TITLE
Make sharing easier

### PR DESCRIPTION
**Pull request by stonerl**
Now Users have just to enter a part of the name. e.g. 'do' for 'John Doe'.
see also: owncloud/core#11256

### CODE REVIEW

**Comment by karlitschek** [comment]
@icewind1991 @schiesbn

**Comment by schiesbn** [comment]
Hm, if we search for any sub-string this can give us a huge list of results. While I can see your point I'm not sure if we want this behaviour... @jancborchardt what do you think from a UX point of view?

**Comment by karlitschek** [comment]
@MTRichards

**Comment by stonerl** [comment]
What is different compared to the standard behavior for local users. E.g. if a local user with the uid "sorcerer" and displayname "Simon Magus" exists in the user-db. Typing "orc", "mon", "ma" and so on will always show this very user in the sharing dialogue. If he is member in the group "wizards" typing "wiz", "iza" or "ds" will show the group. The changes I made are reproduce the behavior that is currently present in the OC core.

**Comment by MTRichards** [comment]
Problem comes when we have large groups / users that need to be pulled from LDAP to search the string. That has been an issue in the past, the massive performance impact of wildcard share name searches when sharing a doc or searching for a user.

**Comment by stonerl** [comment]
OK thank you for the clarification. So I should add a backendcheck?

**Comment by stonerl** [comment]
Sorry just one more question:

```php
array(
'sql' => 'SELECT `uid`, `displayname` FROM `*PREFIX*users_external`'
. ' WHERE (LOWER(`displayname`) LIKE LOWER(?) '
. ' OR LOWER(`uid`) LIKE LOWER(?)) AND `backend` = ?',
'limit' => $limit,
'offset' => $offset
),
array('%' . $search . '%', '%' . $search . '%', $this->backend)
```php

This search just involves the table "*PREFIX*users_external" so there shouldn't be any interference with LDAP, should there?

**Comment by schiesbn** [comment]
@stonerl it depends on which user management is enabled. The table is used for the native ownCloud user management but if a LDAP is involved we query the LDAP.

**Comment by jancborchardt** [comment]
The important part here seems mainly to be able to search for last names of the full name. That is, it’s less important to find `John Doe` when typing in `ohn` (who would do that?) than it is to find him when searching `Doe`.

So basically, the possibility to find inside the full name, starting after each whitespace?

**Comment by blizzz** [comment]
The search is done only in the database. If properly indexed, it still has a performance impact which is not relevant  in small tables. I assume user_external can become big. 

In that case it's probably better to allow the user to prepend the search term with a wildcard to allow this, and don't prepend % by default. 

@jancborchardt certainly makes sense, then we'd extend the SQL query to look for all display names starting with the search term AND all displaynames that have the search term following a white space. This however leaves the potential performance impact (if the table is big).

Technology-wise i'd prefer allowing an wildcard at the start (LDAP backend does it like this), UX-wise @jancborchardt suggestion (not feasible for LDAP, as a comparison).

**Comment by jancborchardt** [comment]
Btw, why is this a pull request to user_external and not to sharing in core?

**Comment by blizzz** [comment]
@jancborchardt looking for users is backend's responsibility

**Comment by jancborchardt** [comment]
Ah k, already works in core anyway.

**Comment by DeepDiver1975** [comment]
ps is against master -> milestone is 8.2

**Comment by DeepDiver1975** [comment]
@blizzz @schiesbn merge or reject? THX

**Comment by nickvergessen** [comment]
Since it matches the behaviour of the user database backend, i'd say merge:
https://github.com/owncloud/core/blob/master/lib/private/user/database.php#L157-L160
https://github.com/owncloud/core/blob/master/lib/private/user/database.php#L239-L240

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by stonerl** [comment]
:bow:

**Pull request merged**
