### PR TITLE
[Stable8.1]Allow seeking for non-public videos. Ref #2087

### PR DESCRIPTION
**Pull request by VicDeo**
Backport of https://github.com/owncloud/apps/pull/2111

### CODE REVIEW

**Comment by VicDeo** [comment]
@PVince81

**Comment by PVince81** [comment]
@VicDeo is there any public video with the correct format that I could use to verify this ?
I saw you mention that not all formats work.

**Comment by PVince81** [comment]
Ah, I just saw your other comment. Will try with big buck bunny :smile:

**Comment by PVince81** [comment]
Tested, works :+1:

**Pull request merged**
