### PR TITLE
Adjust admin_migrate to become config_export

### PR DESCRIPTION
**Pull request by tomneedham**
@LukasReschke @jnfrmarks @karlitschek

### CODE REVIEW

**Comment by jancborchardt** [comment]
What’s the call here @DeepDiver1975 @tomneedham? Merge or close?

**Comment by MorrisJobke** [comment]
I think there are proper ways to export config via occ tool. This was added by @nickvergessen recently AFAIK

**Comment by nickvergessen** [comment]
Yes, `./occ config:list` can be used to display the config in json format

**Comment by karlitschek** [comment]
listing the config with occ in jason format is great. but there is still a usecase for a full export as config.php. especially in the web-interface.

**Comment by MorrisJobke** [comment]
cc @LukasReschke regarding security implications that could have, if you added afterwards other admins to your instance, whom can download the stuff via web.

**Comment by tomneedham** [comment]
Closing - we have `occ` commands and configreport app now.

**Pull request closed without merging**
