### PR TITLE
drop admin_dependencies_check - fixes #2001

### LINKED ISSUE #2001: Drop admin_dependencies_chk
see https://github.com/owncloud/core/issues/13599#issuecomment-71028654

### PR DESCRIPTION
**Pull request by MorrisJobke**
fixes #2001 
Details over there.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @LukasReschke @DeepDiver1975

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Also drop the translations on transifex for this ;)

**Comment by MorrisJobke** [comment]
Ping

**Comment by LukasReschke** [comment]
*PONG*

**Comment by LukasReschke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@nickvergessen @Xenopathic @rullzer Mind to review?

**Comment by rullzer** [comment]
:+1: 
As far as I can tell all the deps are already properly handled in core.

**Comment by MorrisJobke** [comment]
cc @DeepDiver1975 regarding l10n sync

**Pull request merged**
