### PR TITLE
avi files are not supported by this player

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @cdamken

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@LukasReschke Easy one :)

**Comment by LukasReschke** [comment]
@MorrisJobke Does this need a backport?

**Comment by MorrisJobke** [comment]
@LukasReschke @karlitschek Yes a backport to stable8 and stable8.1 would be nice and has a very low risk to break anything.

**Comment by DeepDiver1975** [comment]
> @LukasReschke @karlitschek Yes a backport to stable8 and stable8.1 would be nice and has a very low risk to break anything.

please open PRs - thx

**Comment by MorrisJobke** [comment]
stable8.1 #2091
stable8 #2092

**Pull request merged**
